### ISSUE TITLE
见学长佳作，拜服

### ISSUE THREAD

**Issue by supersahau** [LeeZChuan/DTVis-master#3]
小弟2021毕业生，正踌躇于毕业设计选题。见学长之佳作，不知小弟可否有机会，一观学长的毕业设计论文

**Comment by chentao1998** [comment]
> 小弟2021毕业生，正踌躇于毕业设计选题。见学长之佳作，不知小弟可否有机会，一观学长的毕业设计论文。小弟企鹅:1994195648

**Comment by LeeZChuan** [comment]
如有需要，请邮件与我联系
